filter_secrets: false
language: node_js
node_js: stable
env:
  global:
  - GOOGLE_APPLICATION_CREDENTIALS="${PWD}/client-secret.json"
  - PROJECT_NAME_STG=MayaStaging
  - CLUSTER_NAME_STG=mayadata-production
  - CLOUDSDK_COMPUTE_ZONE=us-central1-a
  - DOCKER_IMAGE_NAME=index.docker.io/mayadata/www-openebs-io
  - KUBE_DEPLOYMENT_NAME=stage-openebs
  - KUBE_DEPLOYMENT_CONTAINER_NAME=stage-openebs
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin
  - COMMIT=${TRAVIS_COMMIT::6}
before_install:
  - npm install -g @angular/cli
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then 
     openssl aes-256-cbc -K $encrypted_b52ccd7b376c_key -iv $encrypted_b52ccd7b376c_iv -in client-secret.json.enc -out client-secret.json -d;
    fi
sudo: required
services:
- docker
before_script:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; 
  fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- gcloud --quiet components update kubectl
- cd openebs-app
- npm install
script:
- ng build --prod
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then export REPO=mayadata/www-openebs-io;
   docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && docker build -t $REPO:$COMMIT . && docker push $REPO; 
  fi
- sleep 7
- cd ..
- "./deploy"

